version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["rails", "server", "-b", "0.0.0.0"]
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: example_password
      POSTGRES_DB: example_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
