default: &default
  adapter: postgresql
  encoding: unicode
  host: db # PostgreSQLサービスのホスト名
  username: postgres
  password: example_password
  database: example_db

development:
  <<: *default
  host: db
